### ISSUE TITLE
week 1 peer review

### ISSUE THREAD

**Issue by EmmaHon** [ErkHal/pocket-pilkki#18]
When starting the game there is no instructions as to how to play the game or any sort of menu screen.  Please add them so it will be easier to play it. Also might want to fix the issue with the pond twitching when waiting the phone to vibrate.

**Comment by ErkHal** [comment]
Hello @EmmaHon 
These issues are being addressed, however the "twitching" issue that you might have experienced when testing the application, is being caused by ARCore library bugs, and we have no affiliation of the developers of ARCore. Instructions on the gameplay will be available in the future.
